---
title: Quarto Movies
format:
  html:
    page-layout: full
    theme:
      - united
      - www/styles.scss
    
server: shiny
---

```{r}
#| context: setup
# pkgs -------------------------------------------------------------------------
library(sap)
library(thematic)
library(ragg)
# resources --------------------------------------------------------------------
addResourcePath(
    prefix = 'quarto',
    directoryPath = system.file('www', package = 'sap'))
# options ----------------------------------------------------------------------
options(shiny.useragg = TRUE)
# theme ------------------------------------------------------------------------
thematic::thematic_set_theme(
  theme = thematic::thematic_theme(
    bg = "#070d35", 
    fg = "#FFFFFF", 
    sequential = NA, 
    accent = "#2ee3a4"))
```

```{r}
#| panel: input
mod_var_input_ui("vars")
```

```{r}
#| panel: center
mod_scatter_display_ui("plot")
```

```{r}
#| panel: fill
tags$br()
tags$em(
  "Built using ",
  tags$a(
    img(
      src = "www/quarto.png",
      height = 25,
      width = 90,
      style = "margin:10px 10px"
    ),
    href = "https://quarto.org/docs/interactive/shiny/"
  ),
  "and data from the ",
  tags$a("Building web applications with Shiny", 
    href = "https://rstudio-education.github.io/shiny-course/"),
  "tutorial."
)
```

```{r}
#| context: server

selected_vars <- mod_var_input_server("vars")

mod_scatter_display_server("plot", var_inputs = selected_vars)

```

